"""change_required_env_vars_to_bool

Revision ID: 05ed22ea392c
Revises: 3340111d9578
Create Date: 2026-03-13 18:32:15.490656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '05ed22ea392c'
down_revision: Union[str, None] = '3340111d9578'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_mcp_server', sa.Column('requires_env_vars', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.drop_column('cms_mcp_server', 'required_env_vars')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_mcp_server', sa.Column('required_env_vars', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('cms_mcp_server', 'requires_env_vars')
    # ### end Alembic commands ###
