"""add_notification_feedback_avatar

Revision ID: 3fee92c1c3af
Revises: 64fd24799b3c
Create Date: 2026-03-12 21:33:25.420455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3fee92c1c3af'
down_revision: Union[str, None] = '64fd24799b3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cms_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['cms_organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['cms_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feedback_created', 'cms_feedback', ['created_at'], unique=False)
    op.create_index('ix_feedback_org', 'cms_feedback', ['org_id'], unique=False)
    op.create_index('ix_feedback_status', 'cms_feedback', ['status'], unique=False)
    op.create_index('ix_feedback_user', 'cms_feedback', ['user_id'], unique=False)
    op.create_table('cms_notification',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title_code', sa.String(length=100), nullable=False),
    sa.Column('message_code', sa.String(length=100), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['cms_organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['cms_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_notification_type'), 'cms_notification', ['type'], unique=False)
    op.create_index('ix_notification_created', 'cms_notification', ['created_at'], unique=False)
    op.create_index('ix_notification_user_org', 'cms_notification', ['user_id', 'org_id'], unique=False)
    op.create_index('ix_notification_user_unread', 'cms_notification', ['user_id', 'is_read'], unique=False)
    op.add_column('cms_user', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cms_user', 'avatar_url')
    op.drop_index('ix_notification_user_unread', table_name='cms_notification')
    op.drop_index('ix_notification_user_org', table_name='cms_notification')
    op.drop_index('ix_notification_created', table_name='cms_notification')
    op.drop_index(op.f('ix_cms_notification_type'), table_name='cms_notification')
    op.drop_table('cms_notification')
    op.drop_index('ix_feedback_user', table_name='cms_feedback')
    op.drop_index('ix_feedback_status', table_name='cms_feedback')
    op.drop_index('ix_feedback_org', table_name='cms_feedback')
    op.drop_index('ix_feedback_created', table_name='cms_feedback')
    op.drop_table('cms_feedback')
    # ### end Alembic commands ###
