"""replace_blacklist_with_invite

Revision ID: 64fd24799b3c
Revises: 7dc0760f0f02
Create Date: 2026-03-12 17:01:50.046368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '64fd24799b3c'
down_revision: Union[str, None] = '7dc0760f0f02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cms_invite',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('org_role', sa.String(length=20), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['cms_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['cms_organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_invite_email'), 'cms_invite', ['email'], unique=False)
    op.create_index(op.f('ix_cms_invite_org_id'), 'cms_invite', ['org_id'], unique=False)
    op.create_index(op.f('ix_cms_invite_status'), 'cms_invite', ['status'], unique=False)
    op.create_index(op.f('ix_cms_invite_token'), 'cms_invite', ['token'], unique=True)
    op.drop_index(op.f('ix_cms_blacklist_expires_at'), table_name='cms_blacklist')
    op.drop_index(op.f('ix_cms_blacklist_jti'), table_name='cms_blacklist')
    op.drop_index(op.f('ix_cms_blacklist_user_id'), table_name='cms_blacklist')
    op.drop_table('cms_blacklist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cms_blacklist',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('jti', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('token_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('blacklisted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('cms_blacklist_pkey'))
    )
    op.create_index(op.f('ix_cms_blacklist_user_id'), 'cms_blacklist', ['user_id'], unique=False)
    op.create_index(op.f('ix_cms_blacklist_jti'), 'cms_blacklist', ['jti'], unique=True)
    op.create_index(op.f('ix_cms_blacklist_expires_at'), 'cms_blacklist', ['expires_at'], unique=False)
    op.drop_index(op.f('ix_cms_invite_token'), table_name='cms_invite')
    op.drop_index(op.f('ix_cms_invite_status'), table_name='cms_invite')
    op.drop_index(op.f('ix_cms_invite_org_id'), table_name='cms_invite')
    op.drop_index(op.f('ix_cms_invite_email'), table_name='cms_invite')
    op.drop_table('cms_invite')
    # ### end Alembic commands ###
