"""initial_cms_schema

Revision ID: 7dc0760f0f02
Revises: 
Create Date: 2026-03-12 16:49:59.342783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7dc0760f0f02'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cms_blacklist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('jti', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('token_type', sa.String(length=20), nullable=False),
    sa.Column('blacklisted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_blacklist_expires_at'), 'cms_blacklist', ['expires_at'], unique=False)
    op.create_index(op.f('ix_cms_blacklist_jti'), 'cms_blacklist', ['jti'], unique=True)
    op.create_index(op.f('ix_cms_blacklist_user_id'), 'cms_blacklist', ['user_id'], unique=False)
    op.create_table('cms_content_type',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('app_label', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cms_organization',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('subdomain', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('subdomain')
    )
    op.create_index(op.f('ix_cms_organization_slug'), 'cms_organization', ['slug'], unique=True)
    op.create_table('cms_system_setting',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_system_setting_key'), 'cms_system_setting', ['key'], unique=True)
    op.create_table('cms_ui_component',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('codename', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('component_type', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_ui_component_codename'), 'cms_ui_component', ['codename'], unique=True)
    op.create_table('cms_user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_user_deleted_at'), 'cms_user', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_cms_user_email'), 'cms_user', ['email'], unique=True)
    op.create_index(op.f('ix_cms_user_is_superuser'), 'cms_user', ['is_superuser'], unique=False)
    op.create_table('cms_agent',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('codename', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['cms_organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_agent_codename'), 'cms_agent', ['codename'], unique=True)
    op.create_index(op.f('ix_cms_agent_org_id'), 'cms_agent', ['org_id'], unique=False)
    op.create_table('cms_audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['cms_organization.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['cms_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_audit_log_action'), 'cms_audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_cms_audit_log_org_id'), 'cms_audit_log', ['org_id'], unique=False)
    op.create_index(op.f('ix_cms_audit_log_resource_type'), 'cms_audit_log', ['resource_type'], unique=False)
    op.create_index(op.f('ix_cms_audit_log_user_id'), 'cms_audit_log', ['user_id'], unique=False)
    op.create_table('cms_folder',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('access_type', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['cms_organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['cms_folder.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_folder_org_id'), 'cms_folder', ['org_id'], unique=False)
    op.create_index(op.f('ix_cms_folder_parent_id'), 'cms_folder', ['parent_id'], unique=False)
    op.create_table('cms_group',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['cms_organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_group_org_id'), 'cms_group', ['org_id'], unique=False)
    op.create_table('cms_mcp_server',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('codename', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('transport', sa.String(length=50), nullable=False),
    sa.Column('connection_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['cms_organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_mcp_server_codename'), 'cms_mcp_server', ['codename'], unique=True)
    op.create_index(op.f('ix_cms_mcp_server_org_id'), 'cms_mcp_server', ['org_id'], unique=False)
    op.create_table('cms_oauth_connection',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('token_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes', sa.String(length=500), nullable=True),
    sa.Column('provider_account_id', sa.String(length=255), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['cms_organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['cms_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_oauth_connection_org_id'), 'cms_oauth_connection', ['org_id'], unique=False)
    op.create_index(op.f('ix_cms_oauth_connection_user_id'), 'cms_oauth_connection', ['user_id'], unique=False)
    op.create_table('cms_org_membership',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('org_role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['cms_organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['cms_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_org_membership_org_id'), 'cms_org_membership', ['org_id'], unique=False)
    op.create_index(op.f('ix_cms_org_membership_user_id'), 'cms_org_membership', ['user_id'], unique=False)
    op.create_table('cms_permission',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content_type_id', sa.UUID(), nullable=False),
    sa.Column('codename', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['content_type_id'], ['cms_content_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_permission_codename'), 'cms_permission', ['codename'], unique=True)
    op.create_index(op.f('ix_cms_permission_content_type_id'), 'cms_permission', ['content_type_id'], unique=False)
    op.create_table('cms_provider',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('api_base_url', sa.String(length=500), nullable=True),
    sa.Column('auth_type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['cms_organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_provider_org_id'), 'cms_provider', ['org_id'], unique=False)
    op.create_index(op.f('ix_cms_provider_slug'), 'cms_provider', ['slug'], unique=True)
    op.create_table('cms_agent_model',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('model_type', sa.String(length=20), nullable=False),
    sa.Column('context_window', sa.Integer(), nullable=True),
    sa.Column('pricing_per_1m_tokens', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['cms_provider.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_agent_model_provider_id'), 'cms_agent_model', ['provider_id'], unique=False)
    op.create_table('cms_document',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('folder_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('access_type', sa.String(length=20), nullable=False),
    sa.Column('index_status', sa.String(length=20), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['cms_folder.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['cms_organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['cms_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_document_folder_id'), 'cms_document', ['folder_id'], unique=False)
    op.create_index(op.f('ix_cms_document_index_status'), 'cms_document', ['index_status'], unique=False)
    op.create_index(op.f('ix_cms_document_org_id'), 'cms_document', ['org_id'], unique=False)
    op.create_table('cms_group_permissions',
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['cms_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permission_id'], ['cms_permission.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'permission_id')
    )
    op.create_table('cms_org_agent',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('config_override', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['cms_agent.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['cms_organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_org_agent_agent_id'), 'cms_org_agent', ['agent_id'], unique=False)
    op.create_index(op.f('ix_cms_org_agent_org_id'), 'cms_org_agent', ['org_id'], unique=False)
    op.create_table('cms_provider_key',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cooldown_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['cms_organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['cms_provider.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_provider_key_org_id'), 'cms_provider_key', ['org_id'], unique=False)
    op.create_index(op.f('ix_cms_provider_key_provider_id'), 'cms_provider_key', ['provider_id'], unique=False)
    op.create_table('cms_resource_permission',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('is_granted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['cms_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['cms_organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permission_id'], ['cms_permission.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['cms_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_resource_permission_org_id'), 'cms_resource_permission', ['org_id'], unique=False)
    op.create_index(op.f('ix_cms_resource_permission_permission_id'), 'cms_resource_permission', ['permission_id'], unique=False)
    op.create_index(op.f('ix_cms_resource_permission_resource_id'), 'cms_resource_permission', ['resource_id'], unique=False)
    op.create_index(op.f('ix_cms_resource_permission_resource_type'), 'cms_resource_permission', ['resource_type'], unique=False)
    op.create_table('cms_tool',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mcp_server_id', sa.UUID(), nullable=False),
    sa.Column('codename', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mcp_server_id'], ['cms_mcp_server.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_tool_codename'), 'cms_tool', ['codename'], unique=True)
    op.create_index(op.f('ix_cms_tool_mcp_server_id'), 'cms_tool', ['mcp_server_id'], unique=False)
    op.create_table('cms_user_groups',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['cms_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['cms_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.create_table('cms_user_permissions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('is_granted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['cms_organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permission_id'], ['cms_permission.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['cms_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'permission_id', 'org_id')
    )
    op.create_table('cms_agent_knowledge',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('folder_id', sa.UUID(), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['cms_agent.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['cms_document.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['folder_id'], ['cms_folder.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['cms_organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_agent_knowledge_agent_id'), 'cms_agent_knowledge', ['agent_id'], unique=False)
    op.create_index(op.f('ix_cms_agent_knowledge_org_id'), 'cms_agent_knowledge', ['org_id'], unique=False)
    op.create_table('cms_agent_provider',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('config_override', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['cms_agent.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_id'], ['cms_agent_model.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['cms_organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['cms_provider.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_agent_provider_agent_id'), 'cms_agent_provider', ['agent_id'], unique=False)
    op.create_index(op.f('ix_cms_agent_provider_org_id'), 'cms_agent_provider', ['org_id'], unique=False)
    op.create_table('cms_document_access',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('folder_id', sa.UUID(), nullable=True),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('can_read', sa.Boolean(), nullable=False),
    sa.Column('can_write', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['cms_document.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['folder_id'], ['cms_folder.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['cms_group.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_document_access_document_id'), 'cms_document_access', ['document_id'], unique=False)
    op.create_index(op.f('ix_cms_document_access_folder_id'), 'cms_document_access', ['folder_id'], unique=False)
    op.create_index(op.f('ix_cms_document_access_group_id'), 'cms_document_access', ['group_id'], unique=False)
    op.create_table('cms_knowledge_index_job',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_chunks', sa.Integer(), nullable=False),
    sa.Column('processed_chunks', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['cms_document.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['cms_organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_knowledge_index_job_document_id'), 'cms_knowledge_index_job', ['document_id'], unique=False)
    op.create_index(op.f('ix_cms_knowledge_index_job_org_id'), 'cms_knowledge_index_job', ['org_id'], unique=False)
    op.create_index(op.f('ix_cms_knowledge_index_job_status'), 'cms_knowledge_index_job', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cms_knowledge_index_job_status'), table_name='cms_knowledge_index_job')
    op.drop_index(op.f('ix_cms_knowledge_index_job_org_id'), table_name='cms_knowledge_index_job')
    op.drop_index(op.f('ix_cms_knowledge_index_job_document_id'), table_name='cms_knowledge_index_job')
    op.drop_table('cms_knowledge_index_job')
    op.drop_index(op.f('ix_cms_document_access_group_id'), table_name='cms_document_access')
    op.drop_index(op.f('ix_cms_document_access_folder_id'), table_name='cms_document_access')
    op.drop_index(op.f('ix_cms_document_access_document_id'), table_name='cms_document_access')
    op.drop_table('cms_document_access')
    op.drop_index(op.f('ix_cms_agent_provider_org_id'), table_name='cms_agent_provider')
    op.drop_index(op.f('ix_cms_agent_provider_agent_id'), table_name='cms_agent_provider')
    op.drop_table('cms_agent_provider')
    op.drop_index(op.f('ix_cms_agent_knowledge_org_id'), table_name='cms_agent_knowledge')
    op.drop_index(op.f('ix_cms_agent_knowledge_agent_id'), table_name='cms_agent_knowledge')
    op.drop_table('cms_agent_knowledge')
    op.drop_table('cms_user_permissions')
    op.drop_table('cms_user_groups')
    op.drop_index(op.f('ix_cms_tool_mcp_server_id'), table_name='cms_tool')
    op.drop_index(op.f('ix_cms_tool_codename'), table_name='cms_tool')
    op.drop_table('cms_tool')
    op.drop_index(op.f('ix_cms_resource_permission_resource_type'), table_name='cms_resource_permission')
    op.drop_index(op.f('ix_cms_resource_permission_resource_id'), table_name='cms_resource_permission')
    op.drop_index(op.f('ix_cms_resource_permission_permission_id'), table_name='cms_resource_permission')
    op.drop_index(op.f('ix_cms_resource_permission_org_id'), table_name='cms_resource_permission')
    op.drop_table('cms_resource_permission')
    op.drop_index(op.f('ix_cms_provider_key_provider_id'), table_name='cms_provider_key')
    op.drop_index(op.f('ix_cms_provider_key_org_id'), table_name='cms_provider_key')
    op.drop_table('cms_provider_key')
    op.drop_index(op.f('ix_cms_org_agent_org_id'), table_name='cms_org_agent')
    op.drop_index(op.f('ix_cms_org_agent_agent_id'), table_name='cms_org_agent')
    op.drop_table('cms_org_agent')
    op.drop_table('cms_group_permissions')
    op.drop_index(op.f('ix_cms_document_org_id'), table_name='cms_document')
    op.drop_index(op.f('ix_cms_document_index_status'), table_name='cms_document')
    op.drop_index(op.f('ix_cms_document_folder_id'), table_name='cms_document')
    op.drop_table('cms_document')
    op.drop_index(op.f('ix_cms_agent_model_provider_id'), table_name='cms_agent_model')
    op.drop_table('cms_agent_model')
    op.drop_index(op.f('ix_cms_provider_slug'), table_name='cms_provider')
    op.drop_index(op.f('ix_cms_provider_org_id'), table_name='cms_provider')
    op.drop_table('cms_provider')
    op.drop_index(op.f('ix_cms_permission_content_type_id'), table_name='cms_permission')
    op.drop_index(op.f('ix_cms_permission_codename'), table_name='cms_permission')
    op.drop_table('cms_permission')
    op.drop_index(op.f('ix_cms_org_membership_user_id'), table_name='cms_org_membership')
    op.drop_index(op.f('ix_cms_org_membership_org_id'), table_name='cms_org_membership')
    op.drop_table('cms_org_membership')
    op.drop_index(op.f('ix_cms_oauth_connection_user_id'), table_name='cms_oauth_connection')
    op.drop_index(op.f('ix_cms_oauth_connection_org_id'), table_name='cms_oauth_connection')
    op.drop_table('cms_oauth_connection')
    op.drop_index(op.f('ix_cms_mcp_server_org_id'), table_name='cms_mcp_server')
    op.drop_index(op.f('ix_cms_mcp_server_codename'), table_name='cms_mcp_server')
    op.drop_table('cms_mcp_server')
    op.drop_index(op.f('ix_cms_group_org_id'), table_name='cms_group')
    op.drop_table('cms_group')
    op.drop_index(op.f('ix_cms_folder_parent_id'), table_name='cms_folder')
    op.drop_index(op.f('ix_cms_folder_org_id'), table_name='cms_folder')
    op.drop_table('cms_folder')
    op.drop_index(op.f('ix_cms_audit_log_user_id'), table_name='cms_audit_log')
    op.drop_index(op.f('ix_cms_audit_log_resource_type'), table_name='cms_audit_log')
    op.drop_index(op.f('ix_cms_audit_log_org_id'), table_name='cms_audit_log')
    op.drop_index(op.f('ix_cms_audit_log_action'), table_name='cms_audit_log')
    op.drop_table('cms_audit_log')
    op.drop_index(op.f('ix_cms_agent_org_id'), table_name='cms_agent')
    op.drop_index(op.f('ix_cms_agent_codename'), table_name='cms_agent')
    op.drop_table('cms_agent')
    op.drop_index(op.f('ix_cms_user_is_superuser'), table_name='cms_user')
    op.drop_index(op.f('ix_cms_user_email'), table_name='cms_user')
    op.drop_index(op.f('ix_cms_user_deleted_at'), table_name='cms_user')
    op.drop_table('cms_user')
    op.drop_index(op.f('ix_cms_ui_component_codename'), table_name='cms_ui_component')
    op.drop_table('cms_ui_component')
    op.drop_index(op.f('ix_cms_system_setting_key'), table_name='cms_system_setting')
    op.drop_table('cms_system_setting')
    op.drop_index(op.f('ix_cms_organization_slug'), table_name='cms_organization')
    op.drop_table('cms_organization')
    op.drop_table('cms_content_type')
    op.drop_index(op.f('ix_cms_blacklist_user_id'), table_name='cms_blacklist')
    op.drop_index(op.f('ix_cms_blacklist_jti'), table_name='cms_blacklist')
    op.drop_index(op.f('ix_cms_blacklist_expires_at'), table_name='cms_blacklist')
    op.drop_table('cms_blacklist')
    # ### end Alembic commands ###
