"""add_agent_access_control_tables

Revision ID: cedb00424a33
Revises: b6b741d3873c
Create Date: 2026-03-13 00:53:40.805491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cedb00424a33'
down_revision: Union[str, None] = 'b6b741d3873c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cms_agent_mcp_server',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('mcp_server_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['cms_agent.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mcp_server_id'], ['cms_mcp_server.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['cms_organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_agent_mcp_server_agent_id'), 'cms_agent_mcp_server', ['agent_id'], unique=False)
    op.create_index(op.f('ix_cms_agent_mcp_server_mcp_server_id'), 'cms_agent_mcp_server', ['mcp_server_id'], unique=False)
    op.create_index(op.f('ix_cms_agent_mcp_server_org_id'), 'cms_agent_mcp_server', ['org_id'], unique=False)
    op.create_table('cms_group_agent',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['cms_agent.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['cms_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['cms_organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_group_agent_agent_id'), 'cms_group_agent', ['agent_id'], unique=False)
    op.create_index(op.f('ix_cms_group_agent_group_id'), 'cms_group_agent', ['group_id'], unique=False)
    op.create_index(op.f('ix_cms_group_agent_org_id'), 'cms_group_agent', ['org_id'], unique=False)
    op.create_table('cms_group_tool_access',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('tool_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['cms_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['cms_organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_id'], ['cms_tool.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_group_tool_access_group_id'), 'cms_group_tool_access', ['group_id'], unique=False)
    op.create_index(op.f('ix_cms_group_tool_access_org_id'), 'cms_group_tool_access', ['org_id'], unique=False)
    op.create_index(op.f('ix_cms_group_tool_access_tool_id'), 'cms_group_tool_access', ['tool_id'], unique=False)
    op.add_column('cms_org_agent', sa.Column('is_public', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cms_org_agent', 'is_public')
    op.drop_index(op.f('ix_cms_group_tool_access_tool_id'), table_name='cms_group_tool_access')
    op.drop_index(op.f('ix_cms_group_tool_access_org_id'), table_name='cms_group_tool_access')
    op.drop_index(op.f('ix_cms_group_tool_access_group_id'), table_name='cms_group_tool_access')
    op.drop_table('cms_group_tool_access')
    op.drop_index(op.f('ix_cms_group_agent_org_id'), table_name='cms_group_agent')
    op.drop_index(op.f('ix_cms_group_agent_group_id'), table_name='cms_group_agent')
    op.drop_index(op.f('ix_cms_group_agent_agent_id'), table_name='cms_group_agent')
    op.drop_table('cms_group_agent')
    op.drop_index(op.f('ix_cms_agent_mcp_server_org_id'), table_name='cms_agent_mcp_server')
    op.drop_index(op.f('ix_cms_agent_mcp_server_mcp_server_id'), table_name='cms_agent_mcp_server')
    op.drop_index(op.f('ix_cms_agent_mcp_server_agent_id'), table_name='cms_agent_mcp_server')
    op.drop_table('cms_agent_mcp_server')
    # ### end Alembic commands ###
