# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import file_service_pb2 as file__service__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in file_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FileServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessDocument = channel.unary_unary(
                '/fileservice.FileService/ProcessDocument',
                request_serializer=file__service__pb2.ProcessDocumentRequest.SerializeToString,
                response_deserializer=file__service__pb2.ProcessDocumentResponse.FromString,
                _registered_method=True)
        self.GetDocumentStatus = channel.unary_unary(
                '/fileservice.FileService/GetDocumentStatus',
                request_serializer=file__service__pb2.GetDocumentStatusRequest.SerializeToString,
                response_deserializer=file__service__pb2.GetDocumentStatusResponse.FromString,
                _registered_method=True)
        self.DeleteDocument = channel.unary_unary(
                '/fileservice.FileService/DeleteDocument',
                request_serializer=file__service__pb2.DeleteDocumentRequest.SerializeToString,
                response_deserializer=file__service__pb2.DeleteDocumentResponse.FromString,
                _registered_method=True)
        self.RetrieveDocument = channel.unary_unary(
                '/fileservice.FileService/RetrieveDocument',
                request_serializer=file__service__pb2.RetrieveDocumentRequest.SerializeToString,
                response_deserializer=file__service__pb2.RetrieveDocumentResponse.FromString,
                _registered_method=True)
        self.KnowledgeSearch = channel.unary_unary(
                '/fileservice.FileService/KnowledgeSearch',
                request_serializer=file__service__pb2.KnowledgeSearchRequest.SerializeToString,
                response_deserializer=file__service__pb2.KnowledgeSearchResponse.FromString,
                _registered_method=True)
        self.ListDocuments = channel.unary_unary(
                '/fileservice.FileService/ListDocuments',
                request_serializer=file__service__pb2.ListDocumentsRequest.SerializeToString,
                response_deserializer=file__service__pb2.ListDocumentsResponse.FromString,
                _registered_method=True)


class FileServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessDocument(self, request, context):
        """Process a document: upload → Hybrid Extract → PageIndex → DB + Milvus
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDocumentStatus(self, request, context):
        """Check processing status of a document
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDocument(self, request, context):
        """Delete a document and its tree/nodes from DB + Milvus
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveDocument(self, request, context):
        """PageIndex reasoning retrieval for a specific uploaded document
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def KnowledgeSearch(self, request, context):
        """Milvus semantic search across all user's knowledge base
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDocuments(self, request, context):
        """List documents for a user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessDocument,
                    request_deserializer=file__service__pb2.ProcessDocumentRequest.FromString,
                    response_serializer=file__service__pb2.ProcessDocumentResponse.SerializeToString,
            ),
            'GetDocumentStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDocumentStatus,
                    request_deserializer=file__service__pb2.GetDocumentStatusRequest.FromString,
                    response_serializer=file__service__pb2.GetDocumentStatusResponse.SerializeToString,
            ),
            'DeleteDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDocument,
                    request_deserializer=file__service__pb2.DeleteDocumentRequest.FromString,
                    response_serializer=file__service__pb2.DeleteDocumentResponse.SerializeToString,
            ),
            'RetrieveDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveDocument,
                    request_deserializer=file__service__pb2.RetrieveDocumentRequest.FromString,
                    response_serializer=file__service__pb2.RetrieveDocumentResponse.SerializeToString,
            ),
            'KnowledgeSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.KnowledgeSearch,
                    request_deserializer=file__service__pb2.KnowledgeSearchRequest.FromString,
                    response_serializer=file__service__pb2.KnowledgeSearchResponse.SerializeToString,
            ),
            'ListDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDocuments,
                    request_deserializer=file__service__pb2.ListDocumentsRequest.FromString,
                    response_serializer=file__service__pb2.ListDocumentsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fileservice.FileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fileservice.FileService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FileService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileservice.FileService/ProcessDocument',
            file__service__pb2.ProcessDocumentRequest.SerializeToString,
            file__service__pb2.ProcessDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDocumentStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileservice.FileService/GetDocumentStatus',
            file__service__pb2.GetDocumentStatusRequest.SerializeToString,
            file__service__pb2.GetDocumentStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileservice.FileService/DeleteDocument',
            file__service__pb2.DeleteDocumentRequest.SerializeToString,
            file__service__pb2.DeleteDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetrieveDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileservice.FileService/RetrieveDocument',
            file__service__pb2.RetrieveDocumentRequest.SerializeToString,
            file__service__pb2.RetrieveDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def KnowledgeSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileservice.FileService/KnowledgeSearch',
            file__service__pb2.KnowledgeSearchRequest.SerializeToString,
            file__service__pb2.KnowledgeSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileservice.FileService/ListDocuments',
            file__service__pb2.ListDocumentsRequest.SerializeToString,
            file__service__pb2.ListDocumentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
