/**
 * Frontend constants — mirrors backend ErrorCode + API config.
 */

export const API_BASE_URL = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8002/api/v1";

/**
 * Backend error codes — maps to i18n keys for user-facing messages.
 * Convention: {DOMAIN}_{ACTION} — e.g. "AGENT_NOT_FOUND" → t("errors.AGENT_NOT_FOUND")
 */
export const ErrorCode = {
    // Auth
    AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
    AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
    AUTH_TOKEN_INVALID: "AUTH_TOKEN_INVALID",
    AUTH_TOKEN_REVOKED: "AUTH_TOKEN_REVOKED",
    AUTH_NOT_AUTHENTICATED: "AUTH_NOT_AUTHENTICATED",
    AUTH_FORBIDDEN: "AUTH_FORBIDDEN",
    AUTH_EMAIL_EXISTS: "AUTH_EMAIL_EXISTS",
    AUTH_ACCOUNT_DISABLED: "AUTH_ACCOUNT_DISABLED",
    AUTH_USER_NOT_FOUND: "AUTH_USER_NOT_FOUND",
    AUTH_REFRESH_TOKEN_INVALID: "AUTH_REFRESH_TOKEN_INVALID",

    // Organization
    ORG_NOT_FOUND: "ORG_NOT_FOUND",
    ORG_SLUG_EXISTS: "ORG_SLUG_EXISTS",
    ORG_MEMBERSHIP_REQUIRED: "ORG_MEMBERSHIP_REQUIRED",
    ORG_MEMBERSHIP_EXISTS: "ORG_MEMBERSHIP_EXISTS",

    // Permission
    PERMISSION_DENIED: "PERMISSION_DENIED",
    PERMISSION_NOT_FOUND: "PERMISSION_NOT_FOUND",

    // User
    USER_NOT_FOUND: "USER_NOT_FOUND",
    USER_EMAIL_EXISTS: "USER_EMAIL_EXISTS",

    // Group
    GROUP_NOT_FOUND: "GROUP_NOT_FOUND",
    GROUP_NAME_EXISTS: "GROUP_NAME_EXISTS",

    // Agent
    AGENT_NOT_FOUND: "AGENT_NOT_FOUND",
    AGENT_DISABLED: "AGENT_DISABLED",
    AGENT_CODENAME_EXISTS: "AGENT_CODENAME_EXISTS",

    // MCP
    MCP_NOT_FOUND: "MCP_NOT_FOUND",
    MCP_CODENAME_EXISTS: "MCP_CODENAME_EXISTS",
    TOOL_NOT_FOUND: "TOOL_NOT_FOUND",

    // Provider
    PROVIDER_NOT_FOUND: "PROVIDER_NOT_FOUND",
    PROVIDER_KEY_EXHAUSTED: "PROVIDER_KEY_EXHAUSTED",
    PROVIDER_KEY_INVALID: "PROVIDER_KEY_INVALID",

    // Knowledge
    FOLDER_NOT_FOUND: "FOLDER_NOT_FOUND",
    DOCUMENT_NOT_FOUND: "DOCUMENT_NOT_FOUND",
    DOCUMENT_UPLOAD_FAILED: "DOCUMENT_UPLOAD_FAILED",
    INDEX_JOB_FAILED: "INDEX_JOB_FAILED",

    // General
    VALIDATION_ERROR: "VALIDATION_ERROR",
    INTERNAL_ERROR: "INTERNAL_ERROR",
    NOT_FOUND: "NOT_FOUND",
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];
